---

- name: "Create Docker extra service : {{ docker_extra_name | mandatory }}"
  ansible.builtin.template:
    src: docker-extra.service.j2
    dest: "/etc/systemd/system/docker-extra_{{ docker_extra_name | mandatory }}.service"
    owner: root
    group: root
    mode: "0644"
  register: docker_extra_service

- name: "(Re)start Docker extra service : {{ docker_extra_name | mandatory }}"
  when: docker_extra_service.changed
  ansible.builtin.systemd:
    state: restarted
    enabled: true
    daemon_reload: true
    name: "docker-extra_{{ docker_extra_name | mandatory }}.service"
